/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: simple.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "simple.pb-c.h"
void   sensor_data__init
                     (SensorData         *message)
{
  static const SensorData init_value = SENSOR_DATA__INIT;
  *message = init_value;
}
size_t sensor_data__get_packed_size
                     (const SensorData *message)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor_data__pack
                     (const SensorData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor_data__pack_to_buffer
                     (const SensorData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SensorData *
       sensor_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SensorData *)
     protobuf_c_message_unpack (&sensor_data__descriptor,
                                allocator, len, data);
}
void   sensor_data__free_unpacked
                     (SensorData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sensor_set__init
                     (SensorSet         *message)
{
  static const SensorSet init_value = SENSOR_SET__INIT;
  *message = init_value;
}
size_t sensor_set__get_packed_size
                     (const SensorSet *message)
{
  assert(message->base.descriptor == &sensor_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sensor_set__pack
                     (const SensorSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sensor_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sensor_set__pack_to_buffer
                     (const SensorSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sensor_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SensorSet *
       sensor_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SensorSet *)
     protobuf_c_message_unpack (&sensor_set__descriptor,
                                allocator, len, data);
}
void   sensor_set__free_unpacked
                     (SensorSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sensor_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pwm_led__init
                     (PwmLed         *message)
{
  static const PwmLed init_value = PWM_LED__INIT;
  *message = init_value;
}
size_t pwm_led__get_packed_size
                     (const PwmLed *message)
{
  assert(message->base.descriptor == &pwm_led__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pwm_led__pack
                     (const PwmLed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pwm_led__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pwm_led__pack_to_buffer
                     (const PwmLed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pwm_led__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PwmLed *
       pwm_led__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PwmLed *)
     protobuf_c_message_unpack (&pwm_led__descriptor,
                                allocator, len, data);
}
void   pwm_led__free_unpacked
                     (PwmLed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pwm_led__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   to_st__init
                     (ToSt         *message)
{
  static const ToSt init_value = TO_ST__INIT;
  *message = init_value;
}
size_t to_st__get_packed_size
                     (const ToSt *message)
{
  assert(message->base.descriptor == &to_st__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t to_st__pack
                     (const ToSt *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &to_st__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t to_st__pack_to_buffer
                     (const ToSt *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &to_st__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ToSt *
       to_st__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ToSt *)
     protobuf_c_message_unpack (&to_st__descriptor,
                                allocator, len, data);
}
void   to_st__free_unpacked
                     (ToSt *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &to_st__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   to_hi__init
                     (ToHi         *message)
{
  static const ToHi init_value = TO_HI__INIT;
  *message = init_value;
}
size_t to_hi__get_packed_size
                     (const ToHi *message)
{
  assert(message->base.descriptor == &to_hi__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t to_hi__pack
                     (const ToHi *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &to_hi__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t to_hi__pack_to_buffer
                     (const ToHi *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &to_hi__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ToHi *
       to_hi__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ToHi *)
     protobuf_c_message_unpack (&to_hi__descriptor,
                                allocator, len, data);
}
void   to_hi__free_unpacked
                     (ToHi *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &to_hi__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   to_host__init
                     (ToHost         *message)
{
  static const ToHost init_value = TO_HOST__INIT;
  *message = init_value;
}
size_t to_host__get_packed_size
                     (const ToHost *message)
{
  assert(message->base.descriptor == &to_host__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t to_host__pack
                     (const ToHost *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &to_host__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t to_host__pack_to_buffer
                     (const ToHost *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &to_host__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ToHost *
       to_host__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ToHost *)
     protobuf_c_message_unpack (&to_host__descriptor,
                                allocator, len, data);
}
void   to_host__free_unpacked
                     (ToHost *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &to_host__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sensor_data__field_descriptors[10] =
{
  {
    "sensor_mac_address",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SensorData, sensor_mac_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorData, has_sensor_type),
    offsetof(SensorData, sensor_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_temperature",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SensorData, has_sensor_temperature),
    offsetof(SensorData, sensor_temperature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_humidity",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(SensorData, has_sensor_humidity),
    offsetof(SensorData, sensor_humidity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "eco2_ppm",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorData, has_eco2_ppm),
    offsetof(SensorData, eco2_ppm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tvoc_ppb",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorData, has_tvoc_ppb),
    offsetof(SensorData, tvoc_ppb),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hall_state",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SensorData, has_hall_state),
    offsetof(SensorData, hall_state),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hall_interrupt",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SensorData, has_hall_interrupt),
    offsetof(SensorData, hall_interrupt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pir_interrupt",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SensorData, has_pir_interrupt),
    offsetof(SensorData, pir_interrupt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_voltage",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorData, has_sensor_voltage),
    offsetof(SensorData, sensor_voltage),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor_data__field_indices_by_name[] = {
  4,   /* field[4] = eco2_ppm */
  7,   /* field[7] = hall_interrupt */
  6,   /* field[6] = hall_state */
  8,   /* field[8] = pir_interrupt */
  3,   /* field[3] = sensor_humidity */
  0,   /* field[0] = sensor_mac_address */
  2,   /* field[2] = sensor_temperature */
  1,   /* field[1] = sensor_type */
  9,   /* field[9] = sensor_voltage */
  5,   /* field[5] = tvoc_ppb */
};
static const ProtobufCIntRange sensor_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor sensor_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SensorData",
  "SensorData",
  "SensorData",
  "",
  sizeof(SensorData),
  10,
  sensor_data__field_descriptors,
  sensor_data__field_indices_by_name,
  1,  sensor_data__number_ranges,
  (ProtobufCMessageInit) sensor_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sensor_set__field_descriptors[7] =
{
  {
    "sensor_mac_address",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SensorSet, sensor_mac_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorSet, has_sensor_type),
    offsetof(SensorSet, sensor_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "interrupt_alarm",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SensorSet, has_interrupt_alarm),
    offsetof(SensorSet, interrupt_alarm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notify_period",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorSet, has_notify_period),
    offsetof(SensorSet, notify_period),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "period_alarm",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(SensorSet, has_period_alarm),
    offsetof(SensorSet, period_alarm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "upper_threshold",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorSet, has_upper_threshold),
    offsetof(SensorSet, upper_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lower_threshold",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SensorSet, has_lower_threshold),
    offsetof(SensorSet, lower_threshold),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sensor_set__field_indices_by_name[] = {
  2,   /* field[2] = interrupt_alarm */
  6,   /* field[6] = lower_threshold */
  3,   /* field[3] = notify_period */
  4,   /* field[4] = period_alarm */
  0,   /* field[0] = sensor_mac_address */
  1,   /* field[1] = sensor_type */
  5,   /* field[5] = upper_threshold */
};
static const ProtobufCIntRange sensor_set__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor sensor_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SensorSet",
  "SensorSet",
  "SensorSet",
  "",
  sizeof(SensorSet),
  7,
  sensor_set__field_descriptors,
  sensor_set__field_indices_by_name,
  1,  sensor_set__number_ranges,
  (ProtobufCMessageInit) sensor_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pwm_led__field_descriptors[4] =
{
  {
    "pwm",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PwmLed, has_pwm),
    offsetof(PwmLed, pwm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "duty",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PwmLed, has_duty),
    offsetof(PwmLed, duty),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "period",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PwmLed, has_period),
    offsetof(PwmLed, period),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(PwmLed, has_enable),
    offsetof(PwmLed, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pwm_led__field_indices_by_name[] = {
  1,   /* field[1] = duty */
  3,   /* field[3] = enable */
  2,   /* field[2] = period */
  0,   /* field[0] = pwm */
};
static const ProtobufCIntRange pwm_led__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor pwm_led__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PwmLed",
  "PwmLed",
  "PwmLed",
  "",
  sizeof(PwmLed),
  4,
  pwm_led__field_descriptors,
  pwm_led__field_indices_by_name,
  1,  pwm_led__number_ranges,
  (ProtobufCMessageInit) pwm_led__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor to_st__field_descriptors[16] =
{
  {
    "l_speed",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToSt, has_l_speed),
    offsetof(ToSt, l_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_speed",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToSt, has_r_speed),
    offsetof(ToSt, r_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "neck_speed",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_neck_speed),
    offsetof(ToSt, neck_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "do_charge",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_do_charge),
    offsetof(ToSt, do_charge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_st_info",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_request_st_info),
    offsetof(ToSt, request_st_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_set",
    200,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToSt, sensor_set),
    &sensor_set__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_1",
    801,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_1),
    offsetof(ToSt, test_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_2",
    802,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_2),
    offsetof(ToSt, test_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_3",
    803,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_3),
    offsetof(ToSt, test_3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_4",
    804,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_4),
    offsetof(ToSt, test_4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_5",
    805,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_5),
    offsetof(ToSt, test_5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_6",
    806,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_6),
    offsetof(ToSt, test_6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_7",
    807,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_7),
    offsetof(ToSt, test_7),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_8",
    808,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_8),
    offsetof(ToSt, test_8),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_9",
    809,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_9),
    offsetof(ToSt, test_9),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_10",
    810,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_test_10),
    offsetof(ToSt, test_10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned to_st__field_indices_by_name[] = {
  3,   /* field[3] = do_charge */
  0,   /* field[0] = l_speed */
  2,   /* field[2] = neck_speed */
  1,   /* field[1] = r_speed */
  4,   /* field[4] = request_st_info */
  5,   /* field[5] = sensor_set */
  6,   /* field[6] = test_1 */
  15,   /* field[15] = test_10 */
  7,   /* field[7] = test_2 */
  8,   /* field[8] = test_3 */
  9,   /* field[9] = test_4 */
  10,   /* field[10] = test_5 */
  11,   /* field[11] = test_6 */
  12,   /* field[12] = test_7 */
  13,   /* field[13] = test_8 */
  14,   /* field[14] = test_9 */
};
static const ProtobufCIntRange to_st__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 100, 4 },
  { 200, 5 },
  { 801, 6 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor to_st__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ToSt",
  "ToSt",
  "ToSt",
  "",
  sizeof(ToSt),
  16,
  to_st__field_descriptors,
  to_st__field_indices_by_name,
  4,  to_st__number_ranges,
  (ProtobufCMessageInit) to_st__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor to_hi__field_descriptors[35] =
{
  {
    "tof",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_tof),
    offsetof(ToHi, tof),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accx",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_accx),
    offsetof(ToHi, accx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accy",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_accy),
    offsetof(ToHi, accy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accz",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_accz),
    offsetof(ToHi, accz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_x",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_gyro_x),
    offsetof(ToHi, gyro_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_y",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_gyro_y),
    offsetof(ToHi, gyro_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_z",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_gyro_z),
    offsetof(ToHi, gyro_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_yaw),
    offsetof(ToHi, yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_pitch),
    offsetof(ToHi, pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roll",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_roll),
    offsetof(ToHi, roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_battery),
    offsetof(ToHi, battery),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lenc",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_lenc),
    offsetof(ToHi, lenc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "renc",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_renc),
    offsetof(ToHi, renc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power_button_pressed",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ToHi, has_power_button_pressed),
    offsetof(ToHi, power_button_pressed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usb_con",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ToHi, has_usb_con),
    offsetof(ToHi, usb_con),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone_public_key",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ToHi, phone_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "do_charge",
    101,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_do_charge),
    offsetof(ToHi, do_charge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video_seq",
    102,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_video_seq),
    offsetof(ToHi, video_seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_mute",
    103,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_set_mute),
    offsetof(ToHi, set_mute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    104,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ToHi, has_audio),
    offsetof(ToHi, audio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_ir_cut1",
    105,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_set_ir_cut1),
    offsetof(ToHi, set_ir_cut1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_ir_cut2",
    106,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_set_ir_cut2),
    offsetof(ToHi, set_ir_cut2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pwm_led",
    300,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHi, pwm_led),
    &pwm_led__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_1",
    801,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_1),
    offsetof(ToHi, test_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_2",
    802,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_2),
    offsetof(ToHi, test_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_3",
    803,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_3),
    offsetof(ToHi, test_3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_4",
    804,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_4),
    offsetof(ToHi, test_4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_5",
    805,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_5),
    offsetof(ToHi, test_5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_6",
    806,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_6),
    offsetof(ToHi, test_6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_7",
    807,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_7),
    offsetof(ToHi, test_7),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_8",
    808,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_8),
    offsetof(ToHi, test_8),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_9",
    809,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_9),
    offsetof(ToHi, test_9),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_10",
    810,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_test_10),
    offsetof(ToHi, test_10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tohost_bypass",
    1000,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHi, tohost_bypass),
    &to_host__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tost_bypass",
    1001,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHi, tost_bypass),
    &to_st__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned to_hi__field_indices_by_name[] = {
  1,   /* field[1] = accx */
  2,   /* field[2] = accy */
  3,   /* field[3] = accz */
  19,   /* field[19] = audio */
  10,   /* field[10] = battery */
  16,   /* field[16] = do_charge */
  4,   /* field[4] = gyro_x */
  5,   /* field[5] = gyro_y */
  6,   /* field[6] = gyro_z */
  11,   /* field[11] = lenc */
  15,   /* field[15] = phone_public_key */
  8,   /* field[8] = pitch */
  13,   /* field[13] = power_button_pressed */
  22,   /* field[22] = pwm_led */
  12,   /* field[12] = renc */
  9,   /* field[9] = roll */
  20,   /* field[20] = set_ir_cut1 */
  21,   /* field[21] = set_ir_cut2 */
  18,   /* field[18] = set_mute */
  23,   /* field[23] = test_1 */
  32,   /* field[32] = test_10 */
  24,   /* field[24] = test_2 */
  25,   /* field[25] = test_3 */
  26,   /* field[26] = test_4 */
  27,   /* field[27] = test_5 */
  28,   /* field[28] = test_6 */
  29,   /* field[29] = test_7 */
  30,   /* field[30] = test_8 */
  31,   /* field[31] = test_9 */
  0,   /* field[0] = tof */
  33,   /* field[33] = tohost_bypass */
  34,   /* field[34] = tost_bypass */
  14,   /* field[14] = usb_con */
  17,   /* field[17] = video_seq */
  7,   /* field[7] = yaw */
};
static const ProtobufCIntRange to_hi__number_ranges[5 + 1] =
{
  { 1, 0 },
  { 100, 15 },
  { 300, 22 },
  { 801, 23 },
  { 1000, 33 },
  { 0, 35 }
};
const ProtobufCMessageDescriptor to_hi__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ToHi",
  "ToHi",
  "ToHi",
  "",
  sizeof(ToHi),
  35,
  to_hi__field_descriptors,
  to_hi__field_indices_by_name,
  5,  to_hi__number_ranges,
  (ProtobufCMessageInit) to_hi__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor to_host__field_descriptors[13] =
{
  {
    "video",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ToHost, has_video),
    offsetof(ToHost, video),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ToHost, has_audio),
    offsetof(ToHost, audio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sensor_data",
    62,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHost, sensor_data),
    &sensor_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_1",
    801,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_1),
    offsetof(ToHost, test_1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_2",
    802,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_2),
    offsetof(ToHost, test_2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_3",
    803,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_3),
    offsetof(ToHost, test_3),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_4",
    804,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_4),
    offsetof(ToHost, test_4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_5",
    805,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_5),
    offsetof(ToHost, test_5),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_6",
    806,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_6),
    offsetof(ToHost, test_6),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_7",
    807,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_7),
    offsetof(ToHost, test_7),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_8",
    808,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_8),
    offsetof(ToHost, test_8),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_9",
    809,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_9),
    offsetof(ToHost, test_9),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "test_10",
    810,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_test_10),
    offsetof(ToHost, test_10),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned to_host__field_indices_by_name[] = {
  1,   /* field[1] = audio */
  2,   /* field[2] = sensor_data */
  3,   /* field[3] = test_1 */
  12,   /* field[12] = test_10 */
  4,   /* field[4] = test_2 */
  5,   /* field[5] = test_3 */
  6,   /* field[6] = test_4 */
  7,   /* field[7] = test_5 */
  8,   /* field[8] = test_6 */
  9,   /* field[9] = test_7 */
  10,   /* field[10] = test_8 */
  11,   /* field[11] = test_9 */
  0,   /* field[0] = video */
};
static const ProtobufCIntRange to_host__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 62, 2 },
  { 801, 3 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor to_host__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ToHost",
  "ToHost",
  "ToHost",
  "",
  sizeof(ToHost),
  13,
  to_host__field_descriptors,
  to_host__field_indices_by_name,
  3,  to_host__number_ranges,
  (ProtobufCMessageInit) to_host__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue st_info__enum_values_by_number[9] =
{
  { "STATUS", "ST_INFO__STATUS", 1 },
  { "TOF", "ST_INFO__TOF", 2 },
  { "ACC", "ST_INFO__ACC", 4 },
  { "GYRO", "ST_INFO__GYRO", 8 },
  { "IMU", "ST_INFO__IMU", 16 },
  { "HOP", "ST_INFO__HOP", 32 },
  { "MOTOR", "ST_INFO__MOTOR", 64 },
  { "ENC", "ST_INFO__ENC", 128 },
  { "BATTERY", "ST_INFO__BATTERY", 256 },
};
static const ProtobufCIntRange st_info__value_ranges[] = {
{1, 0},{4, 2},{8, 3},{16, 4},{32, 5},{64, 6},{128, 7},{256, 8},{0, 9}
};
static const ProtobufCEnumValueIndex st_info__enum_values_by_name[9] =
{
  { "ACC", 2 },
  { "BATTERY", 8 },
  { "ENC", 7 },
  { "GYRO", 3 },
  { "HOP", 5 },
  { "IMU", 4 },
  { "MOTOR", 6 },
  { "STATUS", 0 },
  { "TOF", 1 },
};
const ProtobufCEnumDescriptor st_info__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StInfo",
  "StInfo",
  "StInfo",
  "",
  9,
  st_info__enum_values_by_number,
  9,
  st_info__enum_values_by_name,
  8,
  st_info__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
