/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: simple.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "simple.pb-c.h"
void   firmware_update__init
                     (FirmwareUpdate         *message)
{
  static const FirmwareUpdate init_value = FIRMWARE_UPDATE__INIT;
  *message = init_value;
}
size_t firmware_update__get_packed_size
                     (const FirmwareUpdate *message)
{
  assert(message->base.descriptor == &firmware_update__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firmware_update__pack
                     (const FirmwareUpdate *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firmware_update__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firmware_update__pack_to_buffer
                     (const FirmwareUpdate *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firmware_update__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmwareUpdate *
       firmware_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmwareUpdate *)
     protobuf_c_message_unpack (&firmware_update__descriptor,
                                allocator, len, data);
}
void   firmware_update__free_unpacked
                     (FirmwareUpdate *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firmware_update__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   firmware_update_feedback__init
                     (FirmwareUpdateFeedback         *message)
{
  static const FirmwareUpdateFeedback init_value = FIRMWARE_UPDATE_FEEDBACK__INIT;
  *message = init_value;
}
size_t firmware_update_feedback__get_packed_size
                     (const FirmwareUpdateFeedback *message)
{
  assert(message->base.descriptor == &firmware_update_feedback__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t firmware_update_feedback__pack
                     (const FirmwareUpdateFeedback *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &firmware_update_feedback__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t firmware_update_feedback__pack_to_buffer
                     (const FirmwareUpdateFeedback *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &firmware_update_feedback__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FirmwareUpdateFeedback *
       firmware_update_feedback__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FirmwareUpdateFeedback *)
     protobuf_c_message_unpack (&firmware_update_feedback__descriptor,
                                allocator, len, data);
}
void   firmware_update_feedback__free_unpacked
                     (FirmwareUpdateFeedback *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &firmware_update_feedback__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   smooth_motor_control_deprecated__init
                     (SmoothMotorControlDeprecated         *message)
{
  static const SmoothMotorControlDeprecated init_value = SMOOTH_MOTOR_CONTROL_DEPRECATED__INIT;
  *message = init_value;
}
size_t smooth_motor_control_deprecated__get_packed_size
                     (const SmoothMotorControlDeprecated *message)
{
  assert(message->base.descriptor == &smooth_motor_control_deprecated__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t smooth_motor_control_deprecated__pack
                     (const SmoothMotorControlDeprecated *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &smooth_motor_control_deprecated__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t smooth_motor_control_deprecated__pack_to_buffer
                     (const SmoothMotorControlDeprecated *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &smooth_motor_control_deprecated__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SmoothMotorControlDeprecated *
       smooth_motor_control_deprecated__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SmoothMotorControlDeprecated *)
     protobuf_c_message_unpack (&smooth_motor_control_deprecated__descriptor,
                                allocator, len, data);
}
void   smooth_motor_control_deprecated__free_unpacked
                     (SmoothMotorControlDeprecated *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &smooth_motor_control_deprecated__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rough_motor_control__init
                     (RoughMotorControl         *message)
{
  static const RoughMotorControl init_value = ROUGH_MOTOR_CONTROL__INIT;
  *message = init_value;
}
size_t rough_motor_control__get_packed_size
                     (const RoughMotorControl *message)
{
  assert(message->base.descriptor == &rough_motor_control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rough_motor_control__pack
                     (const RoughMotorControl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rough_motor_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rough_motor_control__pack_to_buffer
                     (const RoughMotorControl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rough_motor_control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RoughMotorControl *
       rough_motor_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RoughMotorControl *)
     protobuf_c_message_unpack (&rough_motor_control__descriptor,
                                allocator, len, data);
}
void   rough_motor_control__free_unpacked
                     (RoughMotorControl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rough_motor_control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   led_control__init
                     (LedControl         *message)
{
  static const LedControl init_value = LED_CONTROL__INIT;
  *message = init_value;
}
size_t led_control__get_packed_size
                     (const LedControl *message)
{
  assert(message->base.descriptor == &led_control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t led_control__pack
                     (const LedControl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &led_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t led_control__pack_to_buffer
                     (const LedControl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &led_control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LedControl *
       led_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LedControl *)
     protobuf_c_message_unpack (&led_control__descriptor,
                                allocator, len, data);
}
void   led_control__free_unpacked
                     (LedControl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &led_control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   encoder_control__init
                     (EncoderControl         *message)
{
  static const EncoderControl init_value = ENCODER_CONTROL__INIT;
  *message = init_value;
}
size_t encoder_control__get_packed_size
                     (const EncoderControl *message)
{
  assert(message->base.descriptor == &encoder_control__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t encoder_control__pack
                     (const EncoderControl *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &encoder_control__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t encoder_control__pack_to_buffer
                     (const EncoderControl *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &encoder_control__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EncoderControl *
       encoder_control__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EncoderControl *)
     protobuf_c_message_unpack (&encoder_control__descriptor,
                                allocator, len, data);
}
void   encoder_control__free_unpacked
                     (EncoderControl *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &encoder_control__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bandwidth_test__init
                     (BandwidthTest         *message)
{
  static const BandwidthTest init_value = BANDWIDTH_TEST__INIT;
  *message = init_value;
}
size_t bandwidth_test__get_packed_size
                     (const BandwidthTest *message)
{
  assert(message->base.descriptor == &bandwidth_test__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bandwidth_test__pack
                     (const BandwidthTest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bandwidth_test__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bandwidth_test__pack_to_buffer
                     (const BandwidthTest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bandwidth_test__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BandwidthTest *
       bandwidth_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BandwidthTest *)
     protobuf_c_message_unpack (&bandwidth_test__descriptor,
                                allocator, len, data);
}
void   bandwidth_test__free_unpacked
                     (BandwidthTest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bandwidth_test__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   to_ble__init
                     (ToBle         *message)
{
  static const ToBle init_value = TO_BLE__INIT;
  *message = init_value;
}
size_t to_ble__get_packed_size
                     (const ToBle *message)
{
  assert(message->base.descriptor == &to_ble__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t to_ble__pack
                     (const ToBle *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &to_ble__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t to_ble__pack_to_buffer
                     (const ToBle *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &to_ble__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ToBle *
       to_ble__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ToBle *)
     protobuf_c_message_unpack (&to_ble__descriptor,
                                allocator, len, data);
}
void   to_ble__free_unpacked
                     (ToBle *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &to_ble__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   to_st__init
                     (ToSt         *message)
{
  static const ToSt init_value = TO_ST__INIT;
  *message = init_value;
}
size_t to_st__get_packed_size
                     (const ToSt *message)
{
  assert(message->base.descriptor == &to_st__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t to_st__pack
                     (const ToSt *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &to_st__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t to_st__pack_to_buffer
                     (const ToSt *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &to_st__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ToSt *
       to_st__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ToSt *)
     protobuf_c_message_unpack (&to_st__descriptor,
                                allocator, len, data);
}
void   to_st__free_unpacked
                     (ToSt *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &to_st__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   req_complete_setup__init
                     (ReqCompleteSetup         *message)
{
  static const ReqCompleteSetup init_value = REQ_COMPLETE_SETUP__INIT;
  *message = init_value;
}
size_t req_complete_setup__get_packed_size
                     (const ReqCompleteSetup *message)
{
  assert(message->base.descriptor == &req_complete_setup__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t req_complete_setup__pack
                     (const ReqCompleteSetup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &req_complete_setup__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t req_complete_setup__pack_to_buffer
                     (const ReqCompleteSetup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &req_complete_setup__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ReqCompleteSetup *
       req_complete_setup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ReqCompleteSetup *)
     protobuf_c_message_unpack (&req_complete_setup__descriptor,
                                allocator, len, data);
}
void   req_complete_setup__free_unpacked
                     (ReqCompleteSetup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &req_complete_setup__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   to_hi__init
                     (ToHi         *message)
{
  static const ToHi init_value = TO_HI__INIT;
  *message = init_value;
}
size_t to_hi__get_packed_size
                     (const ToHi *message)
{
  assert(message->base.descriptor == &to_hi__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t to_hi__pack
                     (const ToHi *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &to_hi__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t to_hi__pack_to_buffer
                     (const ToHi *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &to_hi__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ToHi *
       to_hi__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ToHi *)
     protobuf_c_message_unpack (&to_hi__descriptor,
                                allocator, len, data);
}
void   to_hi__free_unpacked
                     (ToHi *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &to_hi__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rsp_service_key__init
                     (RspServiceKey         *message)
{
  static const RspServiceKey init_value = RSP_SERVICE_KEY__INIT;
  *message = init_value;
}
size_t rsp_service_key__get_packed_size
                     (const RspServiceKey *message)
{
  assert(message->base.descriptor == &rsp_service_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rsp_service_key__pack
                     (const RspServiceKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rsp_service_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rsp_service_key__pack_to_buffer
                     (const RspServiceKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rsp_service_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RspServiceKey *
       rsp_service_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RspServiceKey *)
     protobuf_c_message_unpack (&rsp_service_key__descriptor,
                                allocator, len, data);
}
void   rsp_service_key__free_unpacked
                     (RspServiceKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rsp_service_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   to_host__init
                     (ToHost         *message)
{
  static const ToHost init_value = TO_HOST__INIT;
  *message = init_value;
}
size_t to_host__get_packed_size
                     (const ToHost *message)
{
  assert(message->base.descriptor == &to_host__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t to_host__pack
                     (const ToHost *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &to_host__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t to_host__pack_to_buffer
                     (const ToHost *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &to_host__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ToHost *
       to_host__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ToHost *)
     protobuf_c_message_unpack (&to_host__descriptor,
                                allocator, len, data);
}
void   to_host__free_unpacked
                     (ToHost *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &to_host__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor firmware_update__field_descriptors[6] =
{
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(FirmwareUpdate, has_data),
    offsetof(FirmwareUpdate, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "verify",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdate, has_verify),
    offsetof(FirmwareUpdate, verify),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdate, has_start),
    offsetof(FirmwareUpdate, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdate, has_end),
    offsetof(FirmwareUpdate, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_offset",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdate, has_start_offset),
    offsetof(FirmwareUpdate, start_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end_offset",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdate, has_end_offset),
    offsetof(FirmwareUpdate, end_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firmware_update__field_indices_by_name[] = {
  0,   /* field[0] = data */
  3,   /* field[3] = end */
  5,   /* field[5] = end_offset */
  2,   /* field[2] = start */
  4,   /* field[4] = start_offset */
  1,   /* field[1] = verify */
};
static const ProtobufCIntRange firmware_update__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor firmware_update__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FirmwareUpdate",
  "FirmwareUpdate",
  "FirmwareUpdate",
  "",
  sizeof(FirmwareUpdate),
  6,
  firmware_update__field_descriptors,
  firmware_update__field_indices_by_name,
  1,  firmware_update__number_ranges,
  (ProtobufCMessageInit) firmware_update__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor firmware_update_feedback__field_descriptors[5] =
{
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdateFeedback, has_data),
    offsetof(FirmwareUpdateFeedback, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "verify",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdateFeedback, has_verify),
    offsetof(FirmwareUpdateFeedback, verify),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdateFeedback, has_start),
    offsetof(FirmwareUpdateFeedback, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdateFeedback, has_end),
    offsetof(FirmwareUpdateFeedback, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crc",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(FirmwareUpdateFeedback, has_crc),
    offsetof(FirmwareUpdateFeedback, crc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned firmware_update_feedback__field_indices_by_name[] = {
  4,   /* field[4] = crc */
  0,   /* field[0] = data */
  3,   /* field[3] = end */
  2,   /* field[2] = start */
  1,   /* field[1] = verify */
};
static const ProtobufCIntRange firmware_update_feedback__number_ranges[1 + 1] =
{
  { 2, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor firmware_update_feedback__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "FirmwareUpdateFeedback",
  "FirmwareUpdateFeedback",
  "FirmwareUpdateFeedback",
  "",
  sizeof(FirmwareUpdateFeedback),
  5,
  firmware_update_feedback__field_descriptors,
  firmware_update_feedback__field_indices_by_name,
  1,  firmware_update_feedback__number_ranges,
  (ProtobufCMessageInit) firmware_update_feedback__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor smooth_motor_control_deprecated__field_descriptors[4] =
{
  {
    "left_motor",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SmoothMotorControlDeprecated, has_left_motor),
    offsetof(SmoothMotorControlDeprecated, left_motor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right_motor",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(SmoothMotorControlDeprecated, has_right_motor),
    offsetof(SmoothMotorControlDeprecated, right_motor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adc_interval",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SmoothMotorControlDeprecated, has_adc_interval),
    offsetof(SmoothMotorControlDeprecated, adc_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "acc_decrease",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(SmoothMotorControlDeprecated, has_acc_decrease),
    offsetof(SmoothMotorControlDeprecated, acc_decrease),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned smooth_motor_control_deprecated__field_indices_by_name[] = {
  3,   /* field[3] = acc_decrease */
  2,   /* field[2] = adc_interval */
  0,   /* field[0] = left_motor */
  1,   /* field[1] = right_motor */
};
static const ProtobufCIntRange smooth_motor_control_deprecated__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor smooth_motor_control_deprecated__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SmoothMotorControlDeprecated",
  "SmoothMotorControlDeprecated",
  "SmoothMotorControlDeprecated",
  "",
  sizeof(SmoothMotorControlDeprecated),
  4,
  smooth_motor_control_deprecated__field_descriptors,
  smooth_motor_control_deprecated__field_indices_by_name,
  1,  smooth_motor_control_deprecated__number_ranges,
  (ProtobufCMessageInit) smooth_motor_control_deprecated__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rough_motor_control__field_descriptors[2] =
{
  {
    "left_motor",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RoughMotorControl, has_left_motor),
    offsetof(RoughMotorControl, left_motor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right_motor",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RoughMotorControl, has_right_motor),
    offsetof(RoughMotorControl, right_motor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rough_motor_control__field_indices_by_name[] = {
  0,   /* field[0] = left_motor */
  1,   /* field[1] = right_motor */
};
static const ProtobufCIntRange rough_motor_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rough_motor_control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RoughMotorControl",
  "RoughMotorControl",
  "RoughMotorControl",
  "",
  sizeof(RoughMotorControl),
  2,
  rough_motor_control__field_descriptors,
  rough_motor_control__field_indices_by_name,
  1,  rough_motor_control__number_ranges,
  (ProtobufCMessageInit) rough_motor_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor led_control__field_descriptors[3] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(LedControl, has_left),
    offsetof(LedControl, left),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(LedControl, has_right),
    offsetof(LedControl, right),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bright",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(LedControl, has_bright),
    offsetof(LedControl, bright),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned led_control__field_indices_by_name[] = {
  2,   /* field[2] = bright */
  0,   /* field[0] = left */
  1,   /* field[1] = right */
};
static const ProtobufCIntRange led_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor led_control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LedControl",
  "LedControl",
  "LedControl",
  "",
  sizeof(LedControl),
  3,
  led_control__field_descriptors,
  led_control__field_indices_by_name,
  1,  led_control__number_ranges,
  (ProtobufCMessageInit) led_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor encoder_control__field_descriptors[2] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EncoderControl, has_left),
    offsetof(EncoderControl, left),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EncoderControl, has_right),
    offsetof(EncoderControl, right),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned encoder_control__field_indices_by_name[] = {
  0,   /* field[0] = left */
  1,   /* field[1] = right */
};
static const ProtobufCIntRange encoder_control__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor encoder_control__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EncoderControl",
  "EncoderControl",
  "EncoderControl",
  "",
  sizeof(EncoderControl),
  2,
  encoder_control__field_descriptors,
  encoder_control__field_indices_by_name,
  1,  encoder_control__number_ranges,
  (ProtobufCMessageInit) encoder_control__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bandwidth_test__field_descriptors[3] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(BandwidthTest, has_data),
    offsetof(BandwidthTest, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "step",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BandwidthTest, has_step),
    offsetof(BandwidthTest, step),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth_by_hi",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(BandwidthTest, has_bandwidth_by_hi),
    offsetof(BandwidthTest, bandwidth_by_hi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bandwidth_test__field_indices_by_name[] = {
  2,   /* field[2] = bandwidth_by_hi */
  0,   /* field[0] = data */
  1,   /* field[1] = step */
};
static const ProtobufCIntRange bandwidth_test__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bandwidth_test__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BandwidthTest",
  "BandwidthTest",
  "BandwidthTest",
  "",
  sizeof(BandwidthTest),
  3,
  bandwidth_test__field_descriptors,
  bandwidth_test__field_indices_by_name,
  1,  bandwidth_test__number_ranges,
  (ProtobufCMessageInit) bandwidth_test__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor to_ble__field_descriptors[5] =
{
  {
    "interval",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToBle, has_interval),
    offsetof(ToBle, interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToBle, has_power),
    offsetof(ToBle, power),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ToBle, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to_hi_from_phone",
    50,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToBle, to_hi_from_phone),
    &to_hi__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to_host_from_hi",
    51,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToBle, to_host_from_hi),
    &to_host__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned to_ble__field_indices_by_name[] = {
  0,   /* field[0] = interval */
  2,   /* field[2] = name */
  1,   /* field[1] = power */
  3,   /* field[3] = to_hi_from_phone */
  4,   /* field[4] = to_host_from_hi */
};
static const ProtobufCIntRange to_ble__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 50, 3 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor to_ble__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ToBle",
  "ToBle",
  "ToBle",
  "",
  sizeof(ToBle),
  5,
  to_ble__field_descriptors,
  to_ble__field_indices_by_name,
  2,  to_ble__number_ranges,
  (ProtobufCMessageInit) to_ble__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor to_st__field_descriptors[14] =
{
  {
    "smooth_motor_control_deprecated",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToSt, smooth_motor_control_deprecated),
    &smooth_motor_control_deprecated__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rough_motor_control",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToSt, rough_motor_control),
    &rough_motor_control__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encoder_control",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToSt, encoder_control),
    &encoder_control__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "led_control",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToSt, led_control),
    &led_control__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auto_charge_control",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ToSt, has_auto_charge_control),
    offsetof(ToSt, auto_charge_control),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "neck_speed",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_neck_speed),
    offsetof(ToSt, neck_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_st_info",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_request_st_info),
    offsetof(ToSt, request_st_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power_command",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_power_command),
    offsetof(ToSt, power_command),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "do_charge",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_do_charge),
    offsetof(ToSt, do_charge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reset_if_no_serial",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToSt, has_reset_if_no_serial),
    offsetof(ToSt, reset_if_no_serial),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loopback",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ToSt, has_loopback),
    offsetof(ToSt, loopback),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stm_update",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToSt, stm_update),
    &firmware_update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ble_update",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToSt, ble_update),
    &firmware_update__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    99,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ToSt, seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned to_st__field_indices_by_name[] = {
  4,   /* field[4] = auto_charge_control */
  12,   /* field[12] = ble_update */
  8,   /* field[8] = do_charge */
  2,   /* field[2] = encoder_control */
  3,   /* field[3] = led_control */
  10,   /* field[10] = loopback */
  5,   /* field[5] = neck_speed */
  7,   /* field[7] = power_command */
  6,   /* field[6] = request_st_info */
  9,   /* field[9] = reset_if_no_serial */
  1,   /* field[1] = rough_motor_control */
  13,   /* field[13] = seq */
  0,   /* field[0] = smooth_motor_control_deprecated */
  11,   /* field[11] = stm_update */
};
static const ProtobufCIntRange to_st__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 99, 13 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor to_st__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ToSt",
  "ToSt",
  "ToSt",
  "",
  sizeof(ToSt),
  14,
  to_st__field_descriptors,
  to_st__field_indices_by_name,
  2,  to_st__number_ranges,
  (ProtobufCMessageInit) to_st__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor req_complete_setup__field_descriptors[2] =
{
  {
    "user_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReqCompleteSetup, user_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ReqCompleteSetup, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned req_complete_setup__field_indices_by_name[] = {
  1,   /* field[1] = device_id */
  0,   /* field[0] = user_id */
};
static const ProtobufCIntRange req_complete_setup__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor req_complete_setup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ReqCompleteSetup",
  "ReqCompleteSetup",
  "ReqCompleteSetup",
  "",
  sizeof(ReqCompleteSetup),
  2,
  req_complete_setup__field_descriptors,
  req_complete_setup__field_indices_by_name,
  1,  req_complete_setup__number_ranges,
  (ProtobufCMessageInit) req_complete_setup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor to_hi__field_descriptors[47] =
{
  {
    "tohost_bypass",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHi, tohost_bypass),
    &to_host__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tost_bypass",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHi, tost_bypass),
    &to_st__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_status),
    offsetof(ToHi, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tof",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_tof),
    offsetof(ToHi, tof),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accx",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_accx),
    offsetof(ToHi, accx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accy",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_accy),
    offsetof(ToHi, accy),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accz",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_accz),
    offsetof(ToHi, accz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_x",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_gyro_x),
    offsetof(ToHi, gyro_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_y",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_gyro_y),
    offsetof(ToHi, gyro_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gyro_z",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_gyro_z),
    offsetof(ToHi, gyro_z),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "yaw",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_yaw),
    offsetof(ToHi, yaw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pitch",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_pitch),
    offsetof(ToHi, pitch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roll",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_roll),
    offsetof(ToHi, roll),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(ToHi, has_battery),
    offsetof(ToHi, battery),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hopadc",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_hopadc),
    offsetof(ToHi, hopadc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lspeed",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_lspeed),
    offsetof(ToHi, lspeed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rspeed",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_rspeed),
    offsetof(ToHi, rspeed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "t_speed",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_t_speed),
    offsetof(ToHi, t_speed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lenc",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_lenc),
    offsetof(ToHi, lenc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "renc",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_renc),
    offsetof(ToHi, renc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "power_button_pressed",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ToHi, has_power_button_pressed),
    offsetof(ToHi, power_button_pressed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usb_con",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ToHi, has_usb_con),
    offsetof(ToHi, usb_con),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "charge_complete",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ToHi, has_charge_complete),
    offsetof(ToHi, charge_complete),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auto_charge_step",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_auto_charge_step),
    offsetof(ToHi, auto_charge_step),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loopback",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ToHi, has_loopback),
    offsetof(ToHi, loopback),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_update_feedback",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHi, firmware_update_feedback),
    &firmware_update_feedback__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone_public_key",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ToHi, phone_public_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "do_charge",
    101,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_do_charge),
    offsetof(ToHi, do_charge),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video_seq",
    102,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_video_seq),
    offsetof(ToHi, video_seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth_test",
    103,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHi, bandwidth_test),
    &bandwidth_test__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_stop_qc",
    104,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_request_stop_qc),
    offsetof(ToHi, request_stop_qc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_mic_loop_back",
    105,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_request_mic_loop_back),
    offsetof(ToHi, request_mic_loop_back),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_invert_vert",
    106,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_set_invert_vert),
    offsetof(ToHi, set_invert_vert),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_invert_horiz",
    107,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_set_invert_horiz),
    offsetof(ToHi, set_invert_horiz),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_mic_vol",
    108,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_set_mic_vol),
    offsetof(ToHi, set_mic_vol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_speaker_vol",
    109,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_set_speaker_vol),
    offsetof(ToHi, set_speaker_vol),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_ir_cut1",
    110,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_set_ir_cut1),
    offsetof(ToHi, set_ir_cut1),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_ir_cut2",
    111,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_set_ir_cut2),
    offsetof(ToHi, set_ir_cut2),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "play_pcm",
    112,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_play_pcm),
    offsetof(ToHi, play_pcm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "set_mute",
    113,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ToHi, has_set_mute),
    offsetof(ToHi, set_mute),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    114,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ToHi, has_audio),
    offsetof(ToHi, audio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qc_retry",
    115,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_qc_retry),
    offsetof(ToHi, qc_retry),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssid",
    200,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ToHi, ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssid_password",
    201,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ToHi, ssid_password),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssid_type",
    202,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ToHi, ssid_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_service_key",
    203,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHi, has_req_service_key),
    offsetof(ToHi, req_service_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "req_complete_setup",
    204,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHi, req_complete_setup),
    &req_complete_setup__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned to_hi__field_indices_by_name[] = {
  4,   /* field[4] = accx */
  5,   /* field[5] = accy */
  6,   /* field[6] = accz */
  40,   /* field[40] = audio */
  23,   /* field[23] = auto_charge_step */
  29,   /* field[29] = bandwidth_test */
  13,   /* field[13] = battery */
  22,   /* field[22] = charge_complete */
  27,   /* field[27] = do_charge */
  25,   /* field[25] = firmware_update_feedback */
  7,   /* field[7] = gyro_x */
  8,   /* field[8] = gyro_y */
  9,   /* field[9] = gyro_z */
  14,   /* field[14] = hopadc */
  18,   /* field[18] = lenc */
  24,   /* field[24] = loopback */
  15,   /* field[15] = lspeed */
  26,   /* field[26] = phone_public_key */
  11,   /* field[11] = pitch */
  38,   /* field[38] = play_pcm */
  20,   /* field[20] = power_button_pressed */
  41,   /* field[41] = qc_retry */
  19,   /* field[19] = renc */
  46,   /* field[46] = req_complete_setup */
  45,   /* field[45] = req_service_key */
  31,   /* field[31] = request_mic_loop_back */
  30,   /* field[30] = request_stop_qc */
  12,   /* field[12] = roll */
  16,   /* field[16] = rspeed */
  33,   /* field[33] = set_invert_horiz */
  32,   /* field[32] = set_invert_vert */
  36,   /* field[36] = set_ir_cut1 */
  37,   /* field[37] = set_ir_cut2 */
  34,   /* field[34] = set_mic_vol */
  39,   /* field[39] = set_mute */
  35,   /* field[35] = set_speaker_vol */
  42,   /* field[42] = ssid */
  43,   /* field[43] = ssid_password */
  44,   /* field[44] = ssid_type */
  2,   /* field[2] = status */
  17,   /* field[17] = t_speed */
  3,   /* field[3] = tof */
  0,   /* field[0] = tohost_bypass */
  1,   /* field[1] = tost_bypass */
  21,   /* field[21] = usb_con */
  28,   /* field[28] = video_seq */
  10,   /* field[10] = yaw */
};
static const ProtobufCIntRange to_hi__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 100, 26 },
  { 200, 42 },
  { 0, 47 }
};
const ProtobufCMessageDescriptor to_hi__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ToHi",
  "ToHi",
  "ToHi",
  "",
  sizeof(ToHi),
  47,
  to_hi__field_descriptors,
  to_hi__field_indices_by_name,
  3,  to_hi__number_ranges,
  (ProtobufCMessageInit) to_hi__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rsp_service_key__field_descriptors[4] =
{
  {
    "service_key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RspServiceKey, service_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac_address",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RspServiceKey, mac_address),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model_name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RspServiceKey, model_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RspServiceKey, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rsp_service_key__field_indices_by_name[] = {
  1,   /* field[1] = mac_address */
  2,   /* field[2] = model_name */
  3,   /* field[3] = serial_number */
  0,   /* field[0] = service_key */
};
static const ProtobufCIntRange rsp_service_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor rsp_service_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RspServiceKey",
  "RspServiceKey",
  "RspServiceKey",
  "",
  sizeof(RspServiceKey),
  4,
  rsp_service_key__field_descriptors,
  rsp_service_key__field_indices_by_name,
  1,  rsp_service_key__number_ranges,
  (ProtobufCMessageInit) rsp_service_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor to_host__field_descriptors[16] =
{
  {
    "video",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ToHost, has_video),
    offsetof(ToHost, video),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "audio",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ToHost, has_audio),
    offsetof(ToHost, audio),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "encrypted_secret_key",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ToHost, has_encrypted_secret_key),
    offsetof(ToHost, encrypted_secret_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video_seq",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_video_seq),
    offsetof(ToHost, video_seq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "video_ts",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_video_ts),
    offsetof(ToHost, video_ts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latency",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_latency),
    offsetof(ToHost, latency),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bitrate",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_bitrate),
    offsetof(ToHost, bitrate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tohi_bypass",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHost, tohi_bypass),
    &to_hi__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_start_qc",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_request_start_qc),
    offsetof(ToHost, request_start_qc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_bandwidth",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_request_bandwidth),
    offsetof(ToHost, request_bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth_test",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHost, bandwidth_test),
    &bandwidth_test__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "debugging_info",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ToHost, debugging_info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_bandwidth_test",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHost, serial_bandwidth_test),
    &bandwidth_test__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "play_pcm_end",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ToHost, has_play_pcm_end),
    offsetof(ToHost, play_pcm_end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsp_service_key",
    100,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ToHost, rsp_service_key),
    &rsp_service_key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rsp_complete_setup",
    101,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ToHost, has_rsp_complete_setup),
    offsetof(ToHost, rsp_complete_setup),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned to_host__field_indices_by_name[] = {
  1,   /* field[1] = audio */
  10,   /* field[10] = bandwidth_test */
  6,   /* field[6] = bitrate */
  11,   /* field[11] = debugging_info */
  2,   /* field[2] = encrypted_secret_key */
  5,   /* field[5] = latency */
  13,   /* field[13] = play_pcm_end */
  9,   /* field[9] = request_bandwidth */
  8,   /* field[8] = request_start_qc */
  15,   /* field[15] = rsp_complete_setup */
  14,   /* field[14] = rsp_service_key */
  12,   /* field[12] = serial_bandwidth_test */
  7,   /* field[7] = tohi_bypass */
  0,   /* field[0] = video */
  3,   /* field[3] = video_seq */
  4,   /* field[4] = video_ts */
};
static const ProtobufCIntRange to_host__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 100, 14 },
  { 0, 16 }
};
const ProtobufCMessageDescriptor to_host__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ToHost",
  "ToHost",
  "ToHost",
  "",
  sizeof(ToHost),
  16,
  to_host__field_descriptors,
  to_host__field_indices_by_name,
  2,  to_host__number_ranges,
  (ProtobufCMessageInit) to_host__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue st_info__enum_values_by_number[9] =
{
  { "STATUS", "ST_INFO__STATUS", 1 },
  { "TOF", "ST_INFO__TOF", 2 },
  { "ACC", "ST_INFO__ACC", 4 },
  { "GYRO", "ST_INFO__GYRO", 8 },
  { "IMU", "ST_INFO__IMU", 16 },
  { "HOP", "ST_INFO__HOP", 32 },
  { "MOTOR", "ST_INFO__MOTOR", 64 },
  { "ENC", "ST_INFO__ENC", 128 },
  { "BATTERY", "ST_INFO__BATTERY", 256 },
};
static const ProtobufCIntRange st_info__value_ranges[] = {
{1, 0},{4, 2},{8, 3},{16, 4},{32, 5},{64, 6},{128, 7},{256, 8},{0, 9}
};
static const ProtobufCEnumValueIndex st_info__enum_values_by_name[9] =
{
  { "ACC", 2 },
  { "BATTERY", 8 },
  { "ENC", 7 },
  { "GYRO", 3 },
  { "HOP", 5 },
  { "IMU", 4 },
  { "MOTOR", 6 },
  { "STATUS", 0 },
  { "TOF", 1 },
};
const ProtobufCEnumDescriptor st_info__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "StInfo",
  "StInfo",
  "StInfo",
  "",
  9,
  st_info__enum_values_by_number,
  9,
  st_info__enum_values_by_name,
  8,
  st_info__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
